project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
]

tracker/urls.py
from django.urls import path

from . import views

app_name = 'tracker'

urlpatterns = [
           path('', views.index, name='home'),
           path('index.html', views.index),
           path('map.html', views.map, name='map'),
           path('sightings.html', views.sightings, name='sightings'),
           path('sightings/add', views.add, name='add'),
           path('stats.html', views.stats, name='stats'),
           path('<Unique_Squirrel_ID>/', views.update, name='update'),
            ]

tracker/models.py
from django.db import models
from django.utils.translation import gettext as _

class Squirrel(models.Model):
   
    Longitude = models.FloatField(
            help_text=_('Longitude'),
            null=False,
            blank=False,
            )

    Latitude = models.FloatField(
            help_text=_('Latitude'),
            null=False,
            blank=False,
            )
   
    Unique_Squirrel_ID = models.CharField(
            max_length=100,
            help_text=_('Unique Squirrel ID'),
            )

    PM = 'PM'
    AM = 'AM'
    Shift_Choices = (
            (PM, _('PM')),
            (AM, _('AM')),
            )
    Shift = models.CharField(
            max_length=2,
            choices=Shift_Choices,
            )

    Date = models.DateField(
            help_text=_('Date Sighted'),
            blank=False,
            )

    Adult = 'Adult'
    Juvenile = 'Juvenile'
    Age_Choices = (
            (Adult, _('Adult')),
            (Juvenile, _('Juvenile')),
            )
    Age = models.CharField(
            max_length=30,
            choices=Age_Choices,
            help_text=_('Age of Squirrel'),
            )

    Gray = 'Gray'
    Cinnamon = 'Cinnamon'
    Black = 'Black'
    Primary_Fur_Color_Choices = (
            (Gray, _('Gray')),
            (Cinnamon, _('Cinnamon')),
            (Black, _('Black')),
            )
    Primary_Fur_Color = models.CharField(
            max_length = 25,
            choices=Primary_Fur_Color_Choices,
            help_text=_('Primary Color of Squirrel'),
            )

    Ground_Plane = 'Ground_Plane'
    Above_Ground = 'Above_Ground'
    Location_Choices = (
            (Ground_Plane, _('Ground_Plane')),
            (Above_Ground, _('Above_Ground')),
            )
    Location = models.CharField(
            max_length=40,
            choices=Location_Choices,
            help_text=_('Location of Squirrel'),
            )

    Specific_Location = models.CharField(
            max_length=1000,
            help_text=_('More specific location of Squirrel'),
            blank = True,
            )

    Running = models.BooleanField(
            help_text=_('Is the Squirrel running'),
            default=False,
            )

    Chasing = models.BooleanField(
            help_text=_('Is the Squirrel chasing'),
            default=False,
            )

    Climbing = models.BooleanField(
            help_text=_('Is the squirrel climbing'),
            default=False,
            )

    Eating = models.BooleanField(
            help_text=_('Is the squirrel eating'),
            default=False,
            )

    Foraging = models.BooleanField(
            help_text=_('Is the squirrel foraging'),
            default=False,
            )
    
    Other_Activities = models.CharField(
            max_length=1000,
            help_text=_('Other activies that the squirrel is doing'),
            blank=True,
            )

    Kuks = models.BooleanField(
            help_text=_('Does the Squirrel Kuk'),
            default=False,
            )

    Quaas = models.BooleanField(
            help_text=_('Does the Squirrel Quaa'),
            default=False,
            )

    Moans = models.BooleanField(
            help_text=_('Does the Squirrel Moan'),
            default=False,
            )

    Tail_flags = models.BooleanField(
            help_text=_('Does the Squirrel have a tail flag'),
            default=False,
            )

    Tail_twitches = models.BooleanField(
            help_text=_('Does the Squirrel tail twitch'),
            default=False,
            )

    Approaches = models.BooleanField(
            help_text=_('Does the Squirrel approach you'),
            default=False,
            )

    Indifferent = models.BooleanField(
            help_text=_('Is the Squirrel indifferent'),
            default=False,
            )

    Runs_from = models.BooleanField(
            help_text=_('Does the Squirrel run from you'),
            default=False,
            )

    def __str__(self):
        return self.Unique_Squirrel_ID






    






# Create your models here.

tracker/forms.py
from tracker.models import Squirrel
from django.forms import ModelForm

class SquirrelAddForm(ModelForm):
    class Meta:
        model = Squirrel
        fields = ['Longitude', 'Latitude', 'Unique_Squirrel_ID', 'Shift', 'Date', 'Age', 'Primary_Fur_Color', 'Location', 'Specific_Location', 'Running', 'Chasing', 'Climbing', 'Eating', 'Foraging', 'Other_Activities',
                  'Kuks', 'Quaas', 'Moans', 'Tail_flags', 'Tail_twitches', 'Approaches', 'Indifferent', 'Runs_from']

tracker/views.py
from django.shortcuts import render
from tracker.models import Squirrel
from django.http import HttpResponse, HttpResponseRedirect
from .forms import SquirrelAddForm



def index(request):
    return render(request, 'tracker/index.html', {})

def map(request):
    squirrels = Squirrel.objects.all()[:100]
    context = {
            'squirrels': squirrels
        }
    return render(request, 'tracker/map.html', context)

def sightings(request):
    squirrels = Squirrel.objects.all().order_by('-Date')
    context = {
            'squirrels': squirrels
            }
    return render(request, 'tracker/sightings.html', context)

def add(request):
    if request.method =='POST':
        form = SquirrelAddForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/sightings.html')
    else:
        form = SquirrelAddForm()
    context = {'form': form}           
    return render(request, 'tracker/add.html', context)

def update(request, Unique_Squirrel_ID):
    squirrel = Squirrel.objects.get(Unique_Squirrel_ID=Unique_Squirrel_ID)
    if request.method =='POST':
        form = SquirrelAddForm(request.POST, instance=squirrel)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/sightings.html')
    else:
        form = SquirrelAddForm(instance=squirrel)
    context = {'form': form}
    return render(request, 'tracker/update.html', context)

def stats(request): 
    total_seen = Squirrel.objects.all().count()
    number_running = Squirrel.objects.filter(Running=True).count()
    number_climbing = Squirrel.objects.filter(Climbing=True).count()
    juvenile_seen = Squirrel.objects.filter(Age='Juvenile').count()
    adults_seen = Squirrel.objects.filter(Age='Adult').count()
   
    context = {
            'total_seen': total_seen,
            'number_running': number_running,
            'number_climbing': number_climbing,
            'juvenile_seen': juvenile_seen,
            'adults_seen': adults_seen,
            }
    return render(request, 'tracker/stats.html', context)

tracker/templates/tracker/add.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <title>Squirrel Tracker Add Sighting</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Main Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Our CSS -->
    {% load static  %}
    <link rel="stylesheet" href="{% static 'sightings/custom.css' %}">
    
  </head>
  <body>

     <nav class="navbar navbar-dark navbar-expand-lg" style="background-color:green">
        <a class="navbar-brand" href="{% url 'tracker:home'  %}">Squirrel Tracker</a>    
        <div class="collapse navbar-collapse" id="navbarColor02">
          <ul class="navbar-nav ml-auto mr-1">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tracker:sightings'  %}">Sightings</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tracker:stats'  %}">Statistics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tracker:map'  %}">Map</a>
            </li>
          </ul>
        </div>
      </nav>
    
      <br>
      <div class="container">
        <h1>Add Squirrel Sighting</h1>
        <hr>
         <form method="post">
              {% csrf_token %}
          
              {{ form.as_p }}
              <br>
              
              <input class="btn btn-primary" type="submit" name="Submit" value="Submit" style="background-color: green">
            </form>
	    <br> 
      </div>
    </div>

<hr>
   
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2020 Natalie Crow and John Kim</p>
    </footer>


</body>
</html>

tracker/templates/tracker/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Squirrel Tracker</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Our CSS -->
    {% load static  %}
    <link rel="stylesheet" href="{% static 'sightings/custom.css' %}">
  </head>

  <!-- BODY ------------------------------------------------- -->
  <body>

<!-- MAIN IMAGE & TITLE -------------------------------------------------------------------------------------->
    
<div class="hero text-center">
    <h1>Squirrel Tracker</h1>        
</div>
<div class="container head">
    <div class="row margin-top-50">
        <div class="col-md-2">
        </div>
    </div>
</div>


<!-- START THE FEATURETTES -->
<div class="container marketing">
    
    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">View, Add, or Update  Squirrel Sightings</h2>
            <p class="lead">Navigate to the sightings where you can: view a list of them all, update one from the list, or even add your own!
                In 2018, over 3,000 sightings were collected in NYC. The original data, from NYC OpenData, can be found <a href="https://data.cityofnewyork.us/Environment/2018-Central-Park-Squirrel-Census-Squirrel-Data/vfnx-vebw" target=_blank>here.</a>
            </p>
            <p><a class="btn btn-secondary" href="sightings.html" role="button" style="background-color: green;">View sightings &raquo;</a></p>
        </div>
        <div class="col-md-5">
		<img src="{% static "sightings/sightings.jpg" %}" class="img-thumbnail">
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">Map of Squirrel Sightings</h2>
            <p class="lead">Zoom in and out of this map to see 100 squirrel sightings plotted. The map starts in Central Park.</p>
            <p><a class="btn btn-secondary" href="map.html" role="button" style="background-color: green">View map &raquo;</a></p>
        </div>
        <div class="col-md-5 order-md-1">
		<img src="{% static "sightings/map.jpg" %}" class="img-thumbnail">
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">Statistics about Squirrel Sightings</h2>
            <p class="lead">Curious about certain demographics of the squirrels sighted so far? Want to see a summary of facts for these squirrels?</p>
            <p><a class="btn btn-secondary" href="{% url 'tracker:stats'  %}" role="button" style="background-color: green">View stats &raquo;</a></p>
        </div>
        <div class="col-md-5">
		<img src="{% static "sightings/stats.jpg" %}" class="img-thumbnail">
        </div>
    </div>

    <hr class="featurette-divider">

<!-- /END THE FEATURETTES -->

</div> <!--end container-->



    <!-- FOOTER -------------------------------------------------------------------------------------->
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2020 Natalie Crow and John Kim</p>
    </footer>
</body>
</html>

tracker/templates/tracker/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <title>Squirrel Tracker Map</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Main Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Our CSS -->
    <link rel="stylesheet" href="custom.css">
    
    <!-- Map Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>

    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>

     <!-- NAVBAR ----------------------------------------------- -->
     <nav class="navbar navbar-dark navbar-expand-lg" style="background-color:green">
      <a class="navbar-brand" href="{% url 'tracker:home'  %}">Squirrel Tracker</a>    
      <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav ml-auto mr-1">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tracker:sightings'  %}">Sightings</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'tracker:stats'  %}">Statistics</a>
          </li>
        </ul>
      </div>
    </nav>


      <!-- Map ----------------------------------------- -->

    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
        40.782091,  // Longitude
        -73.964285  // Latitutde 
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->

        {% for squirrel in squirrels %}
          var point_lat_lon = [{{ squirrel.Latitude }}, {{ squirrel.Longitude }}];
          var marker = L.marker(point_lat_lon).addTo(map);
        {% endfor %}
    </script>
    <hr>
    <!-- FOOTER -------------------------------------------------------------------------------------->
    <footer class="container">
      <p class="float-right"><a href="#">Back to top</a></p>
      <p>&copy; 2020 Natalie Crow and John Kim</p>
  </footer>
</body>
</html>

tracker/templates/tracker/sightings.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <title>Squirrel Tracker Sightings</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Main Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Our CSS -->
    <link rel="stylesheet" href="custom.css">

<style>

.my-custom-scrollbar {
position: relative;
height: 375px;
overflow: auto;
}
.table-wrapper-scroll-y {
display: block;
}

</style>

  </head>
  <body>

     <!-- NAVBAR ----------------------------------------------- -->
     <nav class="navbar navbar-dark navbar-expand-lg" style="background-color:green">
	     <a class="navbar-brand" href="{% url 'tracker:home'  %}">Squirrel Tracker</a>    
        <div class="collapse navbar-collapse" id="navbarColor02">
          <ul class="navbar-nav ml-auto mr-1">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tracker:stats'  %}">Statistics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tracker:map'  %}">Map</a>
            </li>
          </ul>
        </div>
      </nav>

<div class="container"> 

<!-- TABLE ---------------------------- -->
<br>
 <div class="row justify-content-md-center">
	<a href="/sightings/add" role="button" class="btn btn-secondary btn-lg btn-block">Click to add a new sighting</a>
    <hr>
    <div class="table-wrapper-scroll-y my-custom-scrollbar table-responsive-sm" style="padding-top: 40px; padding-bottom: 40px">
    <table class="table table-hover table-bordered">
        <thead class="thead-dark">
            <tr>
              <th scope="col">#ID</th>
              <th scope="col">Date</th>
              <th scope="col">Fur</th>
              <th scope="col">Location</th>
              <th scope="col">Link to edit</th>
            </tr>
          </thead>
          <tbody>
		  {% for squirrel in squirrels %}
            <tr>
		    <td>{{squirrel.Unique_Squirrel_ID}}</td>
		    <td>{{squirrel.Date}}</td>
		    <td>{{squirrel.Primary_Fur_Color}}</td>
		    <td>{{squirrel.Location}}</td>
		    <td><a href="{% url 'tracker:update' squirrel.Unique_Squirrel_ID %}">Edit</a></td>
            </tr>
	    {% endfor %}
          </tbody>
    </table>
</div></div>

</div>
<hr>
    <!-- FOOTER -------------------------------------------------------------------------------------->
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2020 Natalie Crow and John Kim</p>
    </footer>


</body>
</html>

tracker/templates/tracker/stats.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <title>Squirrel Tracker Stats</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

{% load static  %}
<link rel="stylesheet" href="{% static 'sightings/custom.css' %}">
	  
  </head>
  <body>

     <!-- NAVBAR ----------------------------------------------- -->
     <nav class="navbar navbar-dark navbar-expand-lg" style="background-color:green">
        <a class="navbar-brand" href="{% url 'tracker:home'  %}">Squirrel Tracker</a>    
        <div class="collapse navbar-collapse" id="navbarColor02">
          <ul class="navbar-nav ml-auto mr-1">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tracker:sightings'  %}">Sightings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tracker:map'  %}">Map</a>
            </li>
          </ul>
        </div>
      </nav>


<br>
      <div class="pricing header text-center">
  <h1>Squirrel Statistics from Squirrel Sightings</h1>
  <p>Fun facts and stats about the squirrels</p>
</div>

<hr>
  <div class="container">
   <div class="card-deck mb-3 text-center">
     <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4>Total Seen</h4>
      </div>
      <div class="card-body">
        <ul class="list-unstyled">
	 <li>{{total_seen}}</li>
        </ul>
      </div>
    </div>


    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4>Number Running</h4>
      </div>
      <div class="card-body">
	      <ul class="list-unstyled">
	  <li>{{number_running}}</li>
        </ul>
      </div>
    </div>


    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4>Number Climbing</h4>
      </div>
      <div class="card-body">
	      <ul class="list-unstyled">
          <li>{{number_climbing}}</li>
        </ul>
      </div>
    </div>
	
	
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4>Adults Seen</h4>
      </div>
      <div class="card-body">
        <ul class="list-unstyled">
          <li>{{adults_seen}}</li>
        </ul>
      </div>
    </div>
    
    
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4>Juveniles Seen</h4>
      </div>
      <div class="card-body">
	      <ul class="list-unstyled">
          <li>{{juvenile_seen}}</li>
        </ul>
      </div>
    </div>
	 
   </div>  
</div>
<hr>
    <!-- FOOTER -------------------------------------------------------------------------------------->
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2020 Natalie Crow and John Kim</p>
    </footer>

 </body>
</html>

tracker/templates/tracker/update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <title>Squirrel Tracker Update Sighting</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Main Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Our CSS -->
    {% load static  %}
    <link rel="stylesheet" href="{% static 'sightings/custom.css' %}">
    
  </head>
  <body>

     <!-- NAVBAR ------------------------------------------------>
     <nav class="navbar navbar-dark navbar-expand-lg" style="background-color:green">
        <a class="navbar-brand" href="{% url 'tracker:home'  %}">Squirrel Tracker</a>   
        <div class="collapse navbar-collapse" id="navbarColor02">
          <ul class="navbar-nav ml-auto mr-1">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tracker:sightings'  %}">Sightings</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tracker:stats'  %}">Statistics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tracker:map'  %}">Map</a>
            </li>
          </ul>
        </div>
      </nav>
    
      <br>
          <div class="container">
            <h1>Update Squirrel Sighting</h1>
            <hr>
              <form method="post">
                  {% csrf_token %}
              
                  {{ form.as_p }}
                  <br>
                  <input class="btn btn-primary btn-lg" type="submit" name="Submit" value="Update Sighting" style="background-color: green">
                </form>
		<br>
          </div>
        </div>

<hr>
    <!-- FOOTER -------------------------------------------------------------------------------------->
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2020 Natalie Crow and John Kim</p>
    </footer>


</body>
</html>